### ISSUE TITLE
Minimum version

### ISSUE THREAD

**Issue by pcav** [attilaancsin/PolygonSimplifier#3]
Is the >=2.10 requirement a necessity? It would be good to have it for LTR (2.8) too.

**Comment by attilaancsin** [comment]
I don't know. I implemented the plugin on 2.10. I haven't tested it on other versions. I have added this requirement, because I am only sure about that it works on this version.

**Comment by pcav** [comment]
It should work on 2.8 too. Please lower down the min version, I'll do the testing and report eventual issues. If they can't be fixed, we can raise up the min version later.
Thanks.

**Comment by attilaancsin** [comment]
Okay, thanks. I lowered it down to 2.8.

**Comment by pcav** [comment]
Thanks. I still do not see it, could you please upload a new version, or anyway check?

**Comment by attilaancsin** [comment]
I updated the metadata.txt file in the repository. Should I upload a new version too?

**Comment by pcav** [comment]
Yes, please (add an explanation in the changelog).
